application: cardiffcapers
version: v1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(gif|png|jpg|css|js|ico|xml|html))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|css|js|ico|xml|html))

- url: /ajax/.*
  script: controllers.webmethods.app

- url: .*
  script: controllers.main.app

libraries:
- name: webapp2
  version: "2.5.2"
